### ISSUE TITLE
User Can Create an Entry

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/react-code-journal#1]
## 💰 Motivation

Coders will want to capture tidbits they pick up during their research.

## 📐 Plan

Create a responsive form that allows users to store an image URL with some notes about a specific topic.

## 🖼️ Wireframe

![user can create an entry](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/v2/user-can-create-an-entry.png)

## ✅ Task List

- [x] Add a form for creating a journal entry to the `div[data-view="entry-form"]`.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make all inputs of the journal entry form `required`.
- [x] Listen for `'input'` events on the `photoUrl` input to update the `src` attribute of the photo preview when the input value changes.
- [x] Listen for `'submit'` events on the journal entry form and:
  - [x] Put the form's input values into a new object.
  - [x] Reset the image preview's `src' attribute.
  - [x] Reset the form inputs.
- [x] setup express server
- [x] add fetch request to create page
- [x] add post req to index.js
- [x] setup database with pg and postgres
- [x] create schema.sql file
- [x] add sql code to create table
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
