### ISSUE TITLE
User Can View Their Entries

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/react-code-journal#2]
## 💰 Motivation

Once a user records some journal entries, they'll want to see them.

## 📐 Plan

Display the user's journal entries in reverse chronological order so they can see the newest ones first.

## 🖼️ Wireframe

![user can view their entries](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/v2/user-can-view-their-entries.png)

## ✅ Task List

- [x] create entry page 
- [x] add nav bar component
- [x] add link to nav bar for entries
- [x] add page container component
- [x] add hash routing 
- [x] add parseRoute component
- [x] add render page function to app.jsx
- [x] add fetch request to entry page to gather entries in database
- [x] add get request to express server
- [x] add map function to render entries onto page
- [x] Add some dummy journal entries to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the entries list looks good on both mobile and desktop screens.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
