### ISSUE TITLE
User Can Edit An Entry

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/react-code-journal#3]
## 💰 Motivation

If a user makes a mistake when creating an entry or wants to add more notes to an entry, they should be able to edit it.

## 📐 Plan

Allow users to select an existing entry to edit and pre-populate its information into the form.

## 🖼️ Wireframe

![user can edit an entry](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/v2/user-can-edit-an-entry.png)

## ✅ Task List

- [x] Update entry rendering function to include an edit icon for each rendered entry.
- [x] add put request to index.js
- [x] add fetch post request to entries page
- [x] Ensure that each rendered entry is given a unique ID indicating which entry it is.
- [x] Listen for clicks on the parent element of all rendered entries.
- [x] Show the entry form if an edit icon was clicked.
- [x] Pre-populate the entry form with the clicked entry's values from the object found in the props
- [x] Update the entry form's submit handler function to conditionally add a new entry object or update the existing one.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
